add main screen
a-konovalova/GalleryApp pull request #1
Opened 2022-03-03 17:03 UTC by a-konovalova

Closes: Add the main screen of the app. Pictures are displayed on it and when clicked they open in a new screen.

- main screen with gallery grid view added
- mocked data added
- image view screen added

<img src="https://user-images.githubusercontent.com/92645078/158116405-f568069f-2567-4603-a56a-c9ff5ca30ff8.png" width="300"/><img src="https://user-images.githubusercontent.com/92645078/157449279-96e66095-308e-4b82-9040-a3f37cf7132e.png" width="300" />

https://user-images.githubusercontent.com/92645078/157449334-83d1137d-9dcb-4321-bd56-c4320477c158.mp4

2022-03-04 10:14 UTC, viravir commented on GalleryApp/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please make sure that your device-specific settings do not go into version control. Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

2022-03-04 10:41 UTC, gn29 commented on app/src/main/java/com/example/galleryapp/ImageAdapter.kt
> +    override fun getItem(p0: Int): Any {
better to use var name with clear meaning for what it is used, for example if it is picture identifier here so name could be `pictureId` so other team members could understand that without questions

2022-03-04 10:43 UTC, gn29 commented on app/src/main/java/com/example/galleryapp/ImageAdapter.kt
> +        var imageView = view?.findViewById<ImageView>(R.id.imageView)
probably unnecessary null-check because `view == null` already checked in line 34

2022-03-09 10:08 UTC, viravir requested changes
Please provide a video and UI screenshots so that we would be able to inspect them as well.

2022-03-09 10:08 UTC, viravir commented on app/src/main/java/com/example/galleryapp/ImageData.kt
> +object ImageData {
It would be semantically better to have 'Repository' in the name/filename.

2022-03-10 07:33 UTC, viravir commented
Thanks for the video! I suppose it would be better to preserve original photo proportions on the grid (ex: Corgi dog photo cell  looks way too distorted).

2022-03-10 08:05 UTC, viravir commented on app/src/main/java/com/example/galleryapp/ImageViewActivity.kt
> +        val modelItems: Model = intent.getSerializableExtra("data") as Model
'modelItems' means multiple items, but it looks like we have a single record here. Could you find a better name for the variable?

2022-03-10 15:37 UTC, a-konovalova commented on app/src/main/java/com/example/galleryapp/ImageViewActivity.kt
> +    private lateinit var scaleGestureDetector1: ScaleGestureDetector
I used two variables of type ScaleGestureDetector. To distinguish between them, I used numbers, but one is used as a private variable, and the other as a parameter in override fun onScale, so I will rename them to scaleGestureDetector

2022-03-11 07:13 UTC, gn29 commented on GalleryApp/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@a-konovalova 
The solution is:
1. Add folder to .gitignore
2. Remove files from branch. For that:
2.1 remove with command: git rm --cached `git ls-files -i -c --exclude-from=.gitignore`
2.2 commit changes and push to branch

2022-03-11 10:48 UTC, viravir requested changes

2022-03-11 10:48 UTC, viravir commented on app/src/main/java/com/example/galleryapp/ImageViewActivity.kt
> +        buttonBackToMainActivity.setOnClickListener{
Isn't it better to use https://developer.android.com/guide/components/activities/tasks-and-back-stack pop here?

2022-03-14 10:52 UTC, viravir commented on app/src/main/java/com/example/galleryapp/ItemDataRepo.kt
> +class ItemDataRepo: ItemDataRepository {
It's better to add Impl to name, because we need to know whether it's an interface or the implementation by first glance.

2022-03-14 12:39 UTC, viravir approved these changes

2022-03-14 13:40 UTC, merged